```{r, echo=FALSE, results='hide', message=FALSE}
##==============================================================================
## INITIALIZE
##==============================================================================
## Remove all objects; perform garbage collection
rm(list=ls())
gc(reset=TRUE)
## Detach libraries that are not used
geneorama::detach_nonstandard_packages()
## Load libraries that are used
geneorama::loadinstall_libraries(c("data.table", "glmnet", "ggplot2", "splines",
                                   "knitr", "printr", "scales"))
## Load custom functions
geneorama::sourceDir("CODE/functions/")

## Define melt to be the data.table melt
melt <- data.table:::melt.data.table
```

```{r, echo=FALSE, results='hide', fig.show='hide', message=FALSE}
##==============================================================================
## RUN GLMNET MODEL
##==============================================================================

## NOTE: THE DIRECTORY NAME BELOW MUST MATCH YOUR PROECT DIRECTORY NAME
## If you clone the project directly from github.com the project name will
## automatically be food-inspection-evaluation, but if you change the name 
## you will need to update the name of the project below in the set_project_dir
## function below.
geneorama::set_project_dir("food-inspections-evaluation")
geneorama::sourceDir("CODE/functions/")

## Overwrite the base "interactive" function to prevent complete initialization
interactive <- function(){FALSE}
## Source the file that runs the glmnet model:
source("CODE/30_glmnet_model.R", echo = FALSE)
## Remove the temporary local "interactive" function
rm(interactive)
## Remove excess variables generated by "CODE/30_glmnet_model.R"
rm(confusion_values_test, dat, errors, errorsTest, iiTest, iiTrain, 
   lam, mm, pen, w.lam, xmat)

## These should be the only remaining objects (besides functions) imported:
# coef
# inspCoef
# datTest
# model

## List objects (besides functions) to check with comments above:
geneorama::lll()
```



```{r}
opts_chunk$set(tidy = FALSE)
opts_chunk$set(fig.width = 10)
# opts_chunk$set(fig.height = 10)
```


```{r, echo=FALSE, results='hide'}
##==============================================================================
## DEFINE CUSTOM GGPLOT FUNCTION
##==============================================================================

# cbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
#                "#0072B2", "#D55E00", "#CC79A7")

ggplot <- function(...) {
    cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
    ggplot2::ggplot(...) +
        theme_grey()+
        scale_fill_manual(values=cbPalette) +
        scale_colour_manual(values=cbPalette) +
        theme(plot.title = element_text(size = 15))
    
}
```

```{r, echo=FALSE, eval=FALSE}
## Testing palette
# cbPalette <- c("#000000", "#E69F00", "#56B4E9", 
#                "#009E73", "#F0E442", "#0072B2", 
#                "#D55E00", "#CC79A7")
# pie(rep(1,length(cbPalette)), col = cbPalette)
```

## Bar plots

```{r bar_graph_comparing_BAU_and_model_in_first_half}
# datTest[period==1, list(.N, sum(criticalFound))]
# datTest[period_modeled==1, list(.N, sum(criticalFound))]

crit_viol_rate <- data.table(
    Regime = c("Business As Usual", 
               "Data Driven"),
    values = c(datTest[period==1, sum(criticalFound)/.N],
               datTest[period_modeled==1, sum(criticalFound)/.N]))
crit_viol_cumulative <- data.table(
    Regime = c("Business As Usual",
               "Data Driven"),
    values = c(datTest[period==1, sum(criticalFound)] / datTest[ , sum(criticalFound)],
               datTest[period_modeled==1, sum(criticalFound)] / datTest[ , sum(criticalFound)]))

ggplot(crit_viol_rate) + 
    aes(x = Regime, y = values, fill=Regime) + 
    labs(title=paste0('Percentage of inspections resulting in a critical violation\n',
                      'during Period 1\n') ) +
    geom_bar(stat = "identity") + 
    # guides(fill=FALSE) +
    scale_y_continuous(labels = percent) +
    xlab("") + ylab("")

ggplot(crit_viol_cumulative) + 
    aes(x = factor(Regime), y = values, fill=Regime) + 
    labs(title=paste0('Percentage of period 1 & period critical violations\n',
                      'found in Period 1\n') ) +
    geom_bar(stat = "identity") +
    # guides(fill=FALSE) +
    scale_y_continuous(labels = percent) +
    xlab("") + ylab("") + expand_limits(y = 1)
```



## Aggregate count comparisons

```{r}
comp <- cbind(
    datTest[i = order(Inspection_Date), 
            j = list(Inspection_ID_BAU   = Inspection_ID,
                     Inspection_Date   = Inspection_Date,
                     criticalFound_BAU     = criticalFound)],
    datTest[i = order(-glm_pred), 
            j = list(Inspection_ID_Model   = Inspection_ID,
                     criticalFound_Model   = criticalFound)])
comp <- comp[ , Best_Possible := criticalFound_Model[order(-criticalFound_Model)]]
comp <- comp[ , Worst_Possible := criticalFound_Model[order(criticalFound_Model)]]
# comp

comp_summary <- comp[
    i = TRUE, 
    j = list(Total_Inspections = .N,
             Crit_Violations_BAU = sum(criticalFound_BAU),
             Crit_Violations_Model = sum(criticalFound_Model),
             Best_Possible = sum(Best_Possible),
             Worst_Possible = sum(Worst_Possible)), 
    keyby = list(Inspection_Date = Inspection_Date)]
comp_summary
```

## Calculation of average time saved with model

```{r}
date_comp <- merge(
    x = comp[i = TRUE,
             j = list (criticalFound_BAU,
                       date_bau = Inspection_Date,
                       id = Inspection_ID_BAU)],
    y = comp[i = TRUE,
             j = list (criticalFound_Model,
                       date_model = Inspection_Date,
                       id = Inspection_ID_Model)],
    by = "id")
```

### Average improvement based on date comparison

```{r}
date_comp[i = criticalFound_Model==1,
          j = mean(date_model - date_bau)]
```

### Distribution of "how many days sooner" for all critical violations

```{r}
hist(as.numeric(date_comp[criticalFound_Model==1,
          -(date_model - date_bau)]),
     main = paste0("Days sooner that a critical \n",
                   " violation would have been discovered"),
     breaks = 30, 
     xlim = c(-60, 60),
     xlab = "days sooner",
     col = c(rep("#CC79A7", 10), rep("#009E73", 20)))
```

```{r}
hist(as.numeric(date_comp[criticalFound_Model==1,
          -(date_model - date_bau)]),
     main = paste0("Days sooner that a critical \n",
                   " violation would have been discovered"),
     breaks = 5, 
     xlab = "days sooner",
     col = c(rep("#CC79A7", 3), rep("#009E73", 10)))
```



```{r}
comp_summary_percent <- comp_summary[
        i = TRUE,
        j = list(Pct_Crit_Violations_Found_BAU = Crit_Violations_BAU / Total_Inspections,
                 Pct_Crit_Violations_Found_Model = Crit_Violations_Model / Total_Inspections),
        keyby = Inspection_Date]
```

### Unadjusted plot

```{r}
ggplot(melt(data = comp_summary_percent, id.vars = "Inspection_Date")) +
    aes(x=Inspection_Date, y=value, colour=variable) + 
    labs(title=paste0("Percent of inspections resulting in a Critical Violation\n",
                      "(Daily intervals shown)\n"))+
    geom_line()
```

### Plot smoothed by gam to show overall trend

```{r}
ggplot(melt(data = comp_summary_percent, id.vars = "Inspection_Date")) +
    aes(x=Inspection_Date, y=value, colour=variable, fill=variable) + 
    labs(title=paste0('Critical violations found on a daily basis\n',
                      'as a percent of total inspections performed\n',
                      "(smoothed results)\n") ) +
    stat_smooth(method = "gam", 
                formula = y ~ s(x, k=10, sp=2, bs="ps"), 
                alpha=.3,
                level = .65)
```


## Count comparisons (cumulative)


```{r}
comp_summary_cumsum <- comp_summary[
    i = TRUE,
    j = list(`\nInspection Date` = Inspection_Date,
             `Business As Usual` = cumsum(Crit_Violations_BAU),
             `Data Driven` = cumsum(Crit_Violations_Model),
             `Best Possible` = cumsum(Best_Possible),
             `Worst Possible` = cumsum(Worst_Possible))]


ggplot(melt(data = comp_summary_cumsum, 
            id.vars = "\nInspection Date")) +
    aes(x = `\nInspection Date`, 
        y = value, 
        colour = variable) + 
    labs(title="Comparing cumulative violations discovered\n") +
    ylab("Cumulative critical violations to date\n") +
    geom_line(lwd=1.5) + 
    geom_point(colour="black")

```

```{r}
comp_summary_cumsum_diff <- comp_summary_cumsum[
    i = TRUE,
    j = list(Inspection_Date, 
             diff = Model - BAU)]

ggplot(comp_summary_cumsum_diff) +
    aes(x=Inspection_Date, y=diff) + 
    labs(title=paste0("Difference Between BAU and Modeled\n",
                      "Cumulative Critical Violations Found\n")) +
    ylab("Cumulative Difference of Critical Violations Found") +
    geom_line()
# geneorama::clipper(comp_summary)
```



```{r}
comp_summary_cumsum_diff_multi <- comp_summary_cumsum[
    i = TRUE,
    j = list(Inspection_Date, 
             bau_diff = Best_Possible - BAU,
             model_diff = Best_Possible - Model)]

ggplot(melt(comp_summary_cumsum_diff_multi, 
            id.vars = "Inspection_Date")) +
    aes(x=Inspection_Date, y=value, colour=variable) + 
    labs(title=paste0("Difference Between BAU and Modeled\n",
                      "Cumulative Critical Violations Found\n")) +
    ylab("Cumulative Difference of Critical Violations Found") +
    geom_line()
# geneorama::clipper(comp_summary)
```


```{r}
geneorama::set_project_dir("food-inspections-evaluation")
foodInspect <- readRDS("DATA/food_inspections.Rds")
foodInspect <- foodInspect[ , Violations := NULL]

setkey(foodInspect, Inspection_ID)
setkey(date_comp, id)

date_comp_w_name <- foodInspect[,DBA_Name,keyby=Inspection_ID][date_comp]
date_comp_w_name <- date_comp_w_name[ , criticalFound_Model:=NULL]
setnames(date_comp_w_name, "Inspection_ID", "id")
setnames(date_comp_w_name, "DBA_Name", "dba_name")
setnames(date_comp_w_name, "criticalFound_BAU", "crit")

# date_comp_w_name

set.seed(27)
ii <- c(sample(date_comp_w_name[crit==1,id], 5),
        sample(date_comp_w_name[crit==0,id], 20))

samp <- date_comp_w_name[id %in% ii]
samp

plot(data.frame(x = c(1, 1, 3, 3),
                y = c(1, nrow(samp), 1, nrow(samp))),
     type = "n", axes=F, xlab="", ylab="")
samp_dba <- samp[order(samp$date_bau), ]
samp_model <- samp[order(samp$date_model), ]

text(x = 1.5, y = 1:nrow(samp_dba), labels = samp_dba$dba_name, 
     col = ifelse(samp_dba$crit==1,"red", "black") )
text(x = 2.5, y = 1:nrow(samp_model), labels = samp_model$dba_name, 
     col = ifelse(samp_model$crit==1,"red", "black") )

```



